### ISSUE TITLE
Nested tests represented as properly nested rather than individual tests

### ISSUE THREAD

**Issue by netvl** [helmethair-co/scalatest-junit-runner#51]
**Is your feature request related to a problem? Please describe.**

This is not really a big problem, but JUnit 5 supports nested tests natively (which are visible when e.g. you use `@Nested` annotation in the Jupiter API). This results in Gradle formatting tests like
```
TestClassName > Top-level test name > nested test name
```

Additionally, tooling like IDEA understands this format and also displays nested tests in the nested fashion, making the output more readable.

Current implementation of the Scalatest runner, however, results in flat list of tests, even if they use nesting like with `FreeSpec`:

```
class ExampleSpec extends AnyFreeSpec {
  "Top-level test name" - {
    "nested test name" in {
    }
  }
}
```

The test above would be displayed as

```
ExampleSpec > Top-level test name nested test name
```

i.e. the full test name is obtained from its "path" elements, joined with a space. In addition to losing the nesting information (minor inconvenience), this makes tooling like IDEA display all these tests as individual tests, which is moderately inconvenient because it complicates navigation between executed test cases.

**Describe the solution you'd like**

It would be nice for the Scalatest runner produce tests for JUnit, exposing their nesting structure, so the above test would look like this:

```
ExampleSpec > Top-level test name > nested test name
```

in textual output and as a proper tree structure in tooling.

**Describe alternatives you've considered**

Obviously, do nothing - it is not a _very_ big deal, just a convenience issue.

**Additional context**

N/A

**Comment by giurim** [comment]
Hi @netvl, 

thank you very much for your feature request. Indeed, reporting would be much nicer that way. I checked what happens exactly:

This particular test class (ScalaTest has a few) derives from the `Suite` base class via `AnyFreeSpecLike` which holds the structural information about the "nested" tests. Unfortunately this nesting is hidden beyond the structure inside the private `engine:Engine` member and it is not expressed via the standard interface to discover nested suites in the `Suite` superclass:
```
def nestedSuites: collection.immutable.IndexedSeq[Suite] = Vector.empty
```
This function is not overridden anywhere in the inheritance chain of `AnyFreeSpec` and therefore no nested suites could be discovered. 

The tests in the suite are accessed by calling the `testNames()` function and it is implemented in `AnyFreeSpecLike` returning the test names in the less fortunate format you mentioned in your request.

Without handling `AnyFreeSpecLike` specially and accessing the *private* `engine` property of the class (with reflection) I do not see how I would be able to gain access to the inner structure of this suite. It seems it is hidden by design.

I leave this issue open, because someone else might see something I was not able to find or something could change in the interface. 

Thanks again for drawing my attention to this.
