### ISSUE TITLE
Correctly handle Scalatest TagAnnotations

### ISSUE THREAD

**Issue by ivan-lattak** [helmethair-co/scalatest-junit-runner#55]
**Is your feature request related to a problem? Please describe.**
The engine does not respect `org.scalatest.TagAnnotation` annotations on test classes. The tagged test class is executed as if it was not tagged at all.

**Describe the solution you'd like**
I would like the engine to respect these annotations and only execute classes tagged like this when the appropriate `includeTags` modifier is used. Conversely, the engine should not execute classes tagged like this when the tag is mentioned in an `excludeTags` definition.

**Describe alternatives you've considered**
Using `org.scalatest.Tag("<tag>")` is a workaround, however this only works for test functions, not for test methods and whole classes. This means I have to add this Tag object to every function I define.

**Additional context**
N/A

**Comment by giurim** [comment]
Hi @ivan-lattak 

Thank you for your request. I was checking you use case and on my settings it works as it should. Can you elaborate on what your exact setting is?  What version of Scalatest/Gradle you use? Can you provide an example? I added some tagged tests in the [gradle-example](https://github.com/helmethair-co/scalatest-junit-runner/tree/main/gradle-example/src/test/scala/co/helmethair/scalatest/example) project. See `IncludeWithScalaTag`, `SkipWithScalaTag` and  `TaggedTest` classes.

- If `includeTags` is set, only the test enumerated are executed.
- If `excludeTags` is set, the test enumerated are not executed.

I found that when using `org.scalatest.TagAnnotation`, the fully qualified name of the inheriting interface should be used in the settings.

Please let me know if the problem is still persist.
