### ISSUE TITLE
failed assertions in future context show as passing

### ISSUE THREAD

**Issue by gabrieljones** [helmethair-co/scalatest-junit-runner#60]
**Describe the bug**
failed assertions in future context show as passing

**To Reproduce**
```scala
  test("should fail future") {
    val future = Future{
      1
    }

    future.foreach{ r =>
      r should === (2)
    }
  }
```

**Expected behavior**
Should fail

**Build/Test environment:**
 - Gradle 7.1.1
 - Scala 2.13.6
 - Scalatest 3.2.9
 - Junit 1.7.2
 - co.helmethair:scalatest-junit-runner:0.1.9

**Additional context**
This fails correctly in the Intellij ScalaTest runner 
Workaround is to to do assertions on `Await.result` instead of in `future.foreach`

**Comment by giurim** [comment]
Hi Gabriel,

Thank you for the report and the examination. I am away but I will look
into this next week. Intellij might call a different "entry point" hence
the difference in reporting.

Gyuri

**Comment by giurim** [comment]
Hi Gabriel,

I just checked what is going on with this issue. As far as I understand it, this problem falls outside of the scope of the test runner.

The `foreach` function catches all exceptions and reports them to the execution context. In the javadoc it is described as
> Since this method executes asynchronously and does not produce a return value, any non-fatal exceptions thrown will be reported to the ExecutionContext.

The default handler prints a stack-trace but otherwise does nothing else. The type of the `ExecutionContext` used determines how this error will be handled. Also because of the async execution of the lambda of the `foreach`, the test itself already finishes with success when the assertions are running.

I think using `foreach` is not the best approach because of how the error is handled. I am not sure if this is the best solution, but using `map` instead of `foreach` and waiting on the result of the assertions broke the test when the assertion did break:

```
test("should fail future") {
    val future = Future {
      1
    }

    Await.result(
      future.map({ r =>
        r should ===(2)
      }),
      Duration.Inf)
  }
```
  
Let me know if you find anything else to handle these assertions.
Best,
Gyuri
