### ISSUE TITLE
Add support for filters

### ISSUE THREAD

**Issue by giurim** [helmethair-co/scalatest-junit-runner#7]
- package filters
- class filters

**Comment by netvl** [comment]
Any chance for this to be implemented? Right now it seems that simple `./gradlew test --tests 'com.example.SomeSpec' does not work at all. This limits usability and adoption of this plugin, unfortunately :(

**Comment by giurim** [comment]
Hi, thanks for the report, will look into this and get back to you.

**Comment by netvl** [comment]
Btw, after some debugging of what happens with Gradle test filtering (which is unfortunately not very simple), I discovered that it actually _works_, but with caveats.

Curiously, with Gradle (not sure about Maven) the test engines do not really need to implement any custom filtering. Gradle configures all filtering via a [PostDiscoveryFilter](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/PostDiscoveryFilter.html) which is run by the JUnit Launcher itself for all test engines in the same way. This filter basically applies the Gradle's notion of filtering (include and exclude patterns on the `Test` task + command line arguments) to JUnit Platform's `TestDescriptor`s.

The primary problem here is that in Scalatest, it is common for tests to look like this:
```
package com.example

class SomeSpec extends AnyFreeSpec {
  "Some thing" - {
    "does something correctly" in {}
  }
}
```
That is, the "root" group starts with a capital letter (a class name, some textual description, etc). This maps to the following class and method names, as discovered by the test engine:
```
class = com.example.SomeSpec
method = Some thing does something correctly
```
Therefore, the correct way to select just this test would be to write something like
```
./gradlew test --tests 'com.example.SomeSpec.Some thing does something correctly'
```

The issue here is that Gradle applies some heuristics to determine which part of the `--tests` argument is the class name and which is the method name - it basically checks if any part of a `.`-separated string starts with a capital letter, and the latest one which does _before any wildcards_ is considered the class name. So with the above case, Gradle things that the test class name is actually `com.example.SomeSpec.Some` and naturally fails to include the test!

Thankfully, its filtering logic includes special handling of `*`-wildcards. It applies this capitalization-based logic only to the part before the `*` symbol. Therefore, invoking tests like this:
```
./gradlew test --tests 'com.example.SomeSpec.*Some thing does something correctly'
```
solves the problem, and the respective test is discovered. Even further wildcards work, like
```
./gradlew test --tests 'com.example.SomeSpec.*Some thing*correctly'
```

Frankly, this doesn't seem like something the test engine can fix - Gradle does not seem to pass any other kinds of filters to the engine (except tags, but I didn't check how they work). So maybe it would make sense to at least mention this in documentation? Because I do know some people who refrained from using this test engine precisely because they couldn't filter tests on the command line.

**Comment by giurim** [comment]
Wow, thanks for checking! I suspected that the filtering is done in the JUnit code , but I was not sure. I will def. add some part for configuration in the README. Tags should work too but it also need documentation. THanks for the report/investigation.

**Comment by giurim** [comment]
Hi @netvl,

I tried to reproduce the issue to understand it better. I had a plan to mitigate by prefixing the method names with an underscore character. But to me it seems than the Gradle version (6.2.1) of the [gradle-example](https://github.com/helmethair-co/scalatest-junit-runner/tree/main/gradle-example) project is free from this issue. Can you try again with a newer Gradle version?

```
./gradlew clean test --tests 'co.helmethair.scalatest.example.SomeSpec.Some thing does something correctly'
> Task :test
SomeSpec > Some thing does something correctly PASSED

BUILD SUCCESSFUL in 9s
````

**Comment by netvl** [comment]
Hmm, I think I reproduced it on a newer Gradle version, but I'll check again, thanks!

**Comment by giurim** [comment]
If I get it right, this is covering the case you reported and it runs ok
and can be selected:
https://github.com/helmethair-co/scalatest-junit-runner/blob/main/gradle-example/src/test/scala/co/helmethair/scalatest/example/CapitalNameTest.scala

Let me know. I was not able.to reproduce and my guess is the Gradle
version. But it might worth to mention anyways in the readme.
